spring.application.name=magic-shop
server.port=8080
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/shop}
spring.datasource.username=${DB_USERNAME:shop}
spring.datasource.password=${DB_PASSWORD:shop}
