CREATE TABLE users(id BIGSERIAL PRIMARY KEY,username VARCHAR(50) UNIQUE NOT NULL,email VARCHAR(255) UNIQUE NOT NULL,password VARCHAR(255) NOT NULL,display_name VARCHAR(100) NOT NULL,phone VARCHAR(30),role VARCHAR(20) NOT NULL DEFAULT 'USER',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,CHECK(role IN ('USER','ADMIN')));
CREATE TABLE products(id BIGSERIAL PRIMARY KEY,name VARCHAR(255) NOT NULL,description TEXT,price NUMERIC(12,2) NOT NULL CHECK(price>=0),quantity INT NOT NULL DEFAULT 0 CHECK(quantity>=0),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE carts(id BIGSERIAL PRIMARY KEY,user_id BIGINT UNIQUE NOT NULL REFERENCES users(id) ON DELETE CASCADE,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE cart_items(id BIGSERIAL PRIMARY KEY,cart_id BIGINT NOT NULL REFERENCES carts(id) ON DELETE CASCADE,product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,quantity INT NOT NULL CHECK(quantity>0),UNIQUE(cart_id,product_id));
CREATE TABLE orders(id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,status VARCHAR(30) DEFAULT 'NEW',total_price NUMERIC(12,2) NOT NULL,delivery_address TEXT NOT NULL,payment_method VARCHAR(30) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,CHECK(status IN ('NEW','PROCESSING','SHIPPED','COMPLETED','CANCELLED')),CHECK(payment_method IN ('CASH','CARD')));
CREATE TABLE order_items(id BIGSERIAL PRIMARY KEY,order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE RESTRICT,quantity INT NOT NULL CHECK(quantity>0),price NUMERIC(12,2) NOT NULL);
INSERT INTO users(username,email,password,display_name,phone,role) VALUES('admin','admin@magic-shop.local','admin123','Главный магистр','+490000000000','ADMIN'),('wizard','wizard@magic-shop.local','wizard123','Мерлин','+490000000001','USER');
INSERT INTO carts(user_id) SELECT id FROM users WHERE role='USER';
INSERT INTO products(name,description,price,quantity) VALUES('Волшебная палочка','Палочка из древнего дуба.',149.99,15),('Зелье восстановления','Восстанавливает магические силы.',49.99,40),('Зелье невидимости','Позволяет стать невидимым.',199.99,12),('Кристалл маны','Источник магической энергии.',299.99,8),('Амулет защиты','Защищает от тёмной магии.',249.99,10),('Книга заклинаний','Сборник магических заклинаний.',179.99,20),('Мантия волшебника','Мантия с защитными чарами.',129.99,18),('Шляпа великого мага','Шляпа с защитными рунами.',89.99,25),('Зачарованное зеркало','Древний магический артефакт.',399.99,5),('Философский камень','Легендарный артефакт.',999.99,2);
