package com.magicshop.service;
import com.magicshop.model.Models.*;import org.springframework.http.HttpStatus;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.server.ResponseStatusException;import java.math.BigDecimal;import java.util.*;
@Service public class ShopService{
 private final JdbcTemplate db; public ShopService(JdbcTemplate db){this.db=db;}
 private User user(long id){return db.queryForObject("select id,username,email,password,display_name,phone,role from users where id=?",(r,n)->new User(r.getLong(1),r.getString(2),r.getString(3),r.getString(4),r.getString(5),r.getString(6),r.getString(7)),id);}
 public User register(String username,String e,String p,String n,String ph){if(username==null||username.isBlank())throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Логин обязателен");if(db.queryForObject("select count(*) from users where username=?",Integer.class,username)>0)throw new ResponseStatusException(HttpStatus.CONFLICT,"Такой логин уже занят");if(db.queryForObject("select count(*) from users where email=?",Integer.class,e)>0)throw new ResponseStatusException(HttpStatus.CONFLICT,"Email уже занят");long id=db.queryForObject("insert into users(username,email,password,display_name,phone,role) values(?,?,?,?,?, 'USER') returning id",Long.class,username,e,p,n,ph);db.update("insert into carts(user_id) values(?)",id);return user(id);}
 public User login(String login,String p){List<User> u=db.query("select id,username,email,password,display_name,phone,role from users where username=? or email=?",(r,n)->new User(r.getLong(1),r.getString(2),r.getString(3),r.getString(4),r.getString(5),r.getString(6),r.getString(7)),login,login);if(u.isEmpty()||!u.get(0).password().equals(p))throw new ResponseStatusException(HttpStatus.UNAUTHORIZED,"Неверный логин/email или пароль");return u.get(0);}
 public User current(Long id){if(id==null)throw new ResponseStatusException(HttpStatus.UNAUTHORIZED,"Не выполнен вход");return user(id);}
 public List<Product> products(){return db.query("select id,name,description,price,quantity from products order by id",(r,n)->new Product(r.getLong(1),r.getString(2),r.getString(3),r.getBigDecimal(4),r.getInt(5)));}
 private void auth(Long id){if(id==null)throw new ResponseStatusException(HttpStatus.UNAUTHORIZED,"Войдите в аккаунт");}
 public void addCart(long uid,long pid,int q){auth(uid);Product p=db.queryForObject("select id,name,description,price,quantity from products where id=?",(r,n)->new Product(r.getLong(1),r.getString(2),r.getString(3),r.getBigDecimal(4),r.getInt(5)),pid);if(q<1||p.quantity()<q)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Недостаточно товара");db.update("insert into cart_items(cart_id,product_id,quantity) select id,?,? from carts where user_id=? on conflict(cart_id,product_id) do update set quantity=cart_items.quantity+excluded.quantity",pid,q,uid);}
 @Transactional public Order createOrder(long uid,String address,String pay){auth(uid);var rows=db.query("select ci.product_id,ci.quantity,p.price from cart_items ci join carts c on c.id=ci.cart_id join products p on p.id=ci.product_id where c.user_id=?",(r,n)->new Object[]{r.getLong(1),r.getInt(2),r.getBigDecimal(3)},uid);if(rows.isEmpty())throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Корзина пуста");BigDecimal total=BigDecimal.ZERO;for(Object[] x:rows){int q=(int)x[1];BigDecimal price=(BigDecimal)x[2];Integer stock=db.queryForObject("select quantity from products where id=?",Integer.class,(long)x[0]);if(stock<q)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Недостаточно товара");total=total.add(price.multiply(BigDecimal.valueOf(q)));}long oid=db.queryForObject("insert into orders(user_id,status,total_price,delivery_address,payment_method) values(?,'NEW',?,?,?) returning id",Long.class,uid,total,address,pay);for(Object[] x:rows){long pid=(long)x[0];int q=(int)x[1];BigDecimal price=(BigDecimal)x[2];db.update("insert into order_items(order_id,product_id,quantity,price) values(?,?,?,?)",oid,pid,q,price);db.update("update products set quantity=quantity-? where id=?",q,pid);}db.update("delete from cart_items where cart_id=(select id from carts where user_id=?)",uid);return db.queryForObject("select id,user_id,status,total_price,delivery_address,payment_method,created_at from orders where id=?",(r,n)->new Order(r.getLong(1),r.getLong(2),r.getString(3),r.getBigDecimal(4),r.getString(5),r.getString(6),r.getTimestamp(7).toLocalDateTime()),oid);}
 public List<Order> orders(long uid){return db.query("select id,user_id,status,total_price,delivery_address,payment_method,created_at from orders where user_id=? order by created_at desc",(r,n)->new Order(r.getLong(1),r.getLong(2),r.getString(3),r.getBigDecimal(4),r.getString(5),r.getString(6),r.getTimestamp(7).toLocalDateTime()),uid);}
 public List<Order> allOrders(){return db.query("select id,user_id,status,total_price,delivery_address,payment_method,created_at from orders order by created_at desc",(r,n)->new Order(r.getLong(1),r.getLong(2),r.getString(3),r.getBigDecimal(4),r.getString(5),r.getString(6),r.getTimestamp(7).toLocalDateTime()));}
 public void admin(Long uid){auth(uid);if(!"ADMIN".equals(user(uid).role()))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Нет доступа");}
 public void productCreate(Long uid,String n,String d,BigDecimal p,int q){admin(uid);db.update("insert into products(name,description,price,quantity) values(?,?,?,?)",n,d,p,q);}
 public void productUpdate(Long uid,long id,String n,String d,BigDecimal p,int q){admin(uid);db.update("update products set name=?,description=?,price=?,quantity=?,updated_at=current_timestamp where id=?",n,d,p,q,id);}
 public void productDelete(Long uid,long id){admin(uid);db.update("delete from products where id=?",id);}
 public void status(Long uid,long oid,String s){admin(uid);if(!Set.of("NEW","PROCESSING","SHIPPED","COMPLETED","CANCELLED").contains(s))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Неверный статус");db.update("update orders set status=?,updated_at=current_timestamp where id=?",s,oid);}
}
